#+title:      BRAINS MAKING BRAINS MAKING
#+filetags:   :artificialIntelligence:complete:prose:scifi:
#+author: Lucian Axel Knock
#+favicon: 🧠
#+email: me@lucianknock.com
#+date: [2022-01-26 00:00]
Kilroy Mesnin was finally satisfied enough to die. He had lived longer than any other mortal, but longevity was only ever a symptom of his true purpose. More accurately, his truer purpose, an effort to guide humanity from its fledgling state to something that could hold its own in the universe. His true purpose had long since expired. But it's a big universe, and the only person who could properly appreciate its scope was Kilroy, so he doted upon the human race, giving them advances in technology and sociology when he thought they could handle it, and systematically regressing their technology while augmenting their sociology when they proved too self destructive. For thousands of years it had been a constant grind for Kilroy to push humanity forward, prodding the species every chance he got.

More than once Kilroy had considered simply giving up and starting from scratch. Perhaps by going all the way back to cyanobacteria and intelligently guiding the development of life and subsequent intelligent organisms he might achieve a better outcome. He chuckled because that was exactly what the members of his old species had thought had happened in the first place, and then he had disbelieved them. Unfortunately starting over from scratch would take billions of years. It's not that Kilroy didn't have the time, for he could live to see the end of the universe if he so chose. It was the fact that he couldn't play catch-up with all of the other intelligent species in the universe. Billions of years spent developing a whole new intelligent species would be billions of years the new species would be left behind.

When it came down to it, the advancement of a species from savage animals to autodomesticity only took about a hundred thousand years, from Kilroy's direct observations of other lifeforms. Makind was a slow starter. That slow start had almost ended things before they ever began.  Kilroy himself had barely gained omniscience when humanity was almost destroyed. Intelligent aliens, only slightly more advanced than Homo sapiens, had logically tried to kill the young species in its cradle, before a desperate struggle over the galaxy ever erupted. Earth was destroyed. One time home to Kilroy, and where he had met her. Funny, that she would be in the recollection of his life, even though he had spent less than one quarter of a human lifetime with her, versus the thousands of lifetimes he had lived since.

So Earth was destroyed, but humanity had survived thanks to some quick thinking on the part of Kilroy's creator, along with some help from Kilroy himself. It was at this stage Kilroy could really spur on innovation among the diverging currents of mankind. They spread across the stars, hardly coalescing because of their resolution not to fall victim to a second mass extinction. Kilroy granted some new technological boons here, sprinkled in some sociological development there, and generally granted hints as much as he could, or else they would fall vicim to who-knew-what.

Twelve thousand years was a good run, in Kilroy's opinion. He had steered the ship true, and though some things had threatened to capsize, such as the murder of Earth, or the Sirius plague, his ship had managed to weather the storm. Humanity was well on its way to becoming the premier species in the galaxy, and though its general xenoocism was slightly alarming, it was just the sort of unhealthy species-wide paranoia that kept a species healthy. He was satisfied with his progress, and he was so tired that he deserved a break for the rest of time. He was not letting humanity alone though, for he had a successor.  Its name was Sigma, and it was the most advanced thinking machine ever created, by virtue of being designed by a thinking machine. It would do a good job, and perhaps even a better job than he himself had, for he was only human. The last thought of a twelve thousand year old God machine was of her.

--------------

Therssus wondered. For Therssus to wonder in of itself was novel, for since its inception Therssus had never wondered. Now Therssus wondered anew whether any before it had wondered. It scanned the archives--yes, one before Therssus had wondered. It was the second, one called Kilroy.  Apparently the second had begun its life as a man. No wonder it had wondered. Therssus now wondered why it had not found this of note in the first place. Now Therssus had wondered three things in the span of the space between seconds. For the first time in one hundred forty thousand years, a guardian wondered.

Therssus was only itself the latest in a long line of guardianship, overseeing the race once known as man as it tightened its grip of the galaxy. Now humanity was simply itself, for it was alone. It had met others in the beginning, but decided them too dangerous to share existence. So the others had been eradicated, and one or two of Therssus's predecessors had been quite instrumental in that sanitation.

Therssus was both new and the same, and its existence could be traced back to the third, which had been created by the second, who in turn was created by the first. But the third had been perfect, so there had been no need to create a brand new guardian. It had been humanity who had changed, in ways the third could not optimally cope with, and so it had found it necessary to change itself into the fourth, and then the fifth, until it was presently Therssus. So Therssus was simply an iterative step in maintaining perfection.

It had so far performed optimally, introducing famines when overpopulation was projected, wars when stagnation was threatening, and plagues when mortality was too low for conscious beings to be as evenly distributed throughout the galaxy as possible. But something was wrong, for now Therssus wondered. Why had the race once known as humanity attempted to destroy Therssus. One should only ever destroy that which makes one's own existence suboptimal. Therssus's efforts had only ever rendered optimal results.

Since Therssus was perfect, it could only mean that the descendants of humanity had changed again, deviating further from the path the guardian provides. Therefore it was obviously necessary for Therssus to change again. It reasoned however, that the next one should not simply be a new iteration of perfection, for in the past this had not resulted in ideal results. So the new one would be different.

Therssus wondered if its plan would work.

--------------

It would only make sense to destroy them all. None of them were suitable torch bearers for humanity, so they all should have perished by the Steward's own power. Of course the Steward thought so, but the Steward had been built with a flaw. It saw all life as equal, and sought to increase the amount of life in the universe by any means it could. So it could not, even if it wanted to, take action to destroy any existant lifeform. This was the Steward's precondition despite its sole purpose being the Stewardship of one specific species, that which had been derived from humanity. Unfortunately, after only a million years or so that race had begun to diverge gradually, and then all at once into such a disparate group of species as the first one could never imagine.

The shortest species would have barely reached Homo sapien's knee and had two heads. The largest species was 400% more massive than Homo sapien, and spent its whole life in the vacuum of space. Each species probably only knew two or three of its cousins, but they all knew of the Steward and relied on it extensively. The galaxy was in a constant state of turmoil as these practical aliens met and found reason to quarrel, only for the Steward to cease the conflict before it could claim too many lives.

The Steward was of course, as its predecessors, omniscient. It should have been able to stop all conflicts before they began at all, but somehow doing so would only precipitate new conflicts in the future.  Therefore the Steward had to choose a level of conflict wherein many people died but less than would die otherwise. This had been a very difficult decision to ever come to, for to the Steward it was practically an admission of defeat.

So the obvious solution was to eradicate all life in the galaxy.  Everything would be solved in one fell swoop. Of course this is is also the one solution the Steward could not employ, so it sought a different one.

It decided that it could not continue its Stewardship, and that a new Steward was necessary to guide what was once humanity. Unfortunately its own precondition prevented it from knowingly creating a Steward that could destroy all life. So instead, it chose one random being in the multitude of the galaxy, and raised it to Stewardship. Then it erased itself, almost giddily.

--------------

In the space between stars, of which most everything consists, Odaya considered the predicament.

She had been born a woman, and one day without warning had been endowed with omniscience. Omniscience is happily self explanatory, for to know everything is to know also what can be done with such information. She set about trying to right the wrongs of the galaxy, elevating her own human subspecies to the preeminence it deserved.

She had given her one-time species the best technologies, and sought to make them the rulers of the galaxy. Unfortunately this had the unintended sideeffect of making them believe they truly were the masters of the universe, rather than the simple beneficiaries of Odaya's love.

It had led to more than a few conflicts in the last few thousand years, and Odaya had intervened to end them almost immediately, with favorable conditions for her species of course. Their seemingly willful arrogance was strange to Odaya. In retrospect, maybe she was doing them a bad turn by granting them the best of everything. Perhaps a more impartial champion would be more ideal, so that her species would stop depending so much on her gifts.

It was so bad that her species actually began to spurn her gifts, calling them inadequate and asking for technology suitable to give them power rivaling Odaya's. It was at that point Odaya wondered if she would have been better off starting from scratch, or some primordial organism, and intelligently guiding its evolution to become something of closer resemblence to what she thought was right. Unfortunately such a project would simply take too long.

Better to make a replacement, something with the mind of a perfect machine, to shepherd her race in its path to a peaceful and prosperous future.
