#+title: CAR CRASH ADDICT
#+slug: car-crash-addict
#+filetags: :story:complete:comedy:
#+favicon: 🚗
#+date: [2022-02-16 00:00]
#+AUTHOR: Lucian Axel Knock
#+EMAIL: me@lucianknock.com
I can’t stop getting into car crashes. And I don’t mean I have a natural physical propensity for getting into car crashes. I also don’t mean I’m prone to crash because of being a bad driver. I’m actually a pretty good driver, by Californian standards. What I mean is that I have a need to get into car crashes. I can’t say exactly what it is I find so alluring about getting into a car crash, but let me try to explain it to you.

I am extremely wealthy. I am so wealthy that I have trouble putting it into context for other people. I actually went to the effort of finding a suitable way to explain just how wealthy I am. If all my wealth were converted entirely to gold coins, then their collective mass would be equivalent to that of the moon. You might wonder how that is even possible since there isn’t enough gold on Earth to make that many gold coins, but that’s the wonder of our digitized economy.

I own a company that you interact with on a daily basis. You might not even know that you interact with it daily, but it is fairly ubiquitous at this point. This company has grown past the bounds of mere mortal comprehension, and yet I started it, so now I have more money than God. I’m not trying to rub it in or even digress in any way, because my incredible wealth is very central to getting into car crashes.

My favorite form of entertainment is not available to the masses. It is solely reserved for the wealthiest people on the planet. That was sort of how I got into it. You see, before I found what I now refer to as “my pastime,” my life was starting to become quite mundane. I had started a company when I was young and worked hard every single day for decades to make it a success.

Soon though, the company started moving on its own inertia, swallowing up silicon valley startups like a giant blob rolling down the North California coastline. It diversified and made itself indispensable to peoples’ lives, all without my direct intervention. Sure, I still head the ship, and if there are ever any big decisions to be made, I make them. The thing is, those decisions rarely leave me with more than one choice. So one day I found myself significantly older and more tired than I thought I’d ever be, bored out of my mind. The only consolation was unlimited free time and theoretically unlimited wealth. So of course I did what anyone would do. I had a midlife crisis.

It is literally impossible for me to spend more money in an hour than I make in a minute.

But I tried. Extravagance to the extreme fails to come close, and all of the hedonists in history would shudder at the pleasures I indulged in, the ways in which I sought stimulation. I delved deep into sodom and gorged myself on forbidden fruit. Some of the things which I did and took part in would make me physically ill to recount. It suffices to say that hedonism did not help the boredom. Over and over my neurotransmitters returned to normal levels and my synapses went back to firing with even rhythm. Over and over I awoke to a dreary reality in which there was nothing left to achieve, nobody else to compete with, no more worlds to conquer.

One night as I was on my way home from a particularly licentious party I had an interesting thought. I caught myself watching the headlights of each passing car, and wondering what would happen if I turned my steering wheel toward them. *What would happen if I drove headlong into an oncoming car?* I chuckled, because of course I knew what would happen. I have access to the best medical care on Earth, and I could afford to wreck anyone else’s car and buy thousands of replacements. So nothing would happen, *right?* And that thought stuck in my head like a tick, the thought that nothing would happen. That I might be injured, maybe even severely, and I might have to pay for a new car and someone’s funeral, but ultimately I wouldn’t *lose* anything.

I don’t know what really compelled me to do it. It must have been the same thing that made me the wealthiest man ever. Whatever it was, I woke up with sirens blaring in my ears and blurred fire flickering in my vision. It was shocking, the discontinuity that occurred between the moment of the impact and the moment I regained an unsteady consciousness. That jump is what I remember best, the moments preceding the crash and those which immediately followed. Next I awoke in a hospital, and after a lengthy stay I was back to the same boring life as before. Only this time, I had a way out.

You might realize that to get into a car accident once doesn’t exactly cost a fortune. Getting into several crashes a week, however, costs very much.

By the second or third crash, someone started questioning whether I should even be driving. That person and every following person who comes to the same realization either has enough money to make their wildest dreams come true, or considerably less money was spent in making their worst nightmares come true. I don’t know or care which, since that is the point of delegation. I need to delegate a lot to enjoy my pastime. I have a team dedicated to collateral damage who make sure loved ones are compensated, I have a team dedicated to extricating me from any judicial hassles, and I have a team dedicated to providing me the best triage available at any given moment.

In all this I always have the choice of where and when to crash. I can do it whenever I’m on the road and feel like it. I had a quick crash before breakfast this morning, only cost a bruised shin and one funeral fund. In exchange I received something which I can’t quite put into words.

For me it goes beyond something that can be naively expressed. Perhaps I do it for the pure adrenaline that pumps in my veins as I consider when to turn into oncoming traffic. Or maybe I do it for that moment when I wake up alive and there are so many possibilities in a world where I survived a car crash. Whatever it is, I can’t get enough of it, and I won’t stop. I hope I’ve done an adequate job of explaining my pastime to you. If not, then perhaps you’ll understand when we meet on the road some day.
