baseURL = 'https://lucianknock.com/'
languageCode = 'en-us'
title = 'LUCIAN KNOCK'
theme = 'hextra'
enableRobotsTXT = true
enableGitInfo = true
hasCJKLanguage = true
defaultContentLanguage = "en"
enableInlineShortcodes = true

[module.hugoVersion]
extended = true
min = "0.120.3"

[[menu.main]]
  identifier = "STORIES"
  name = "STORIES"
  pageRef = "/stories"
  weight = 2

[[menu.main]]
  identifier = "BLOG"
  name = "BLOG"
  pageRef = "/blog"
  weight = 3

[[menu.main]]
  identifier = "RETROSPECTIVES"
  name = "RETROSPECTIVES"
  pageRef = "/retrospectives"
  weight = 4

[[menu.main]]
  identifier = "BOOKSHELF"
  name = "BOOKSHELF"
  pageRef = "/bookshelf"
  weight = 5
  
# [[menu.main]]
#   identifier = "CONTACT"
#   name = "CONTACT"
#   pageRef = "/contact"
#   weight = 5

# [[menu.main]]
#   identifier = "DEV"
#   name = "DEV"
#   pageRef = "/dev"
#   weight = 4

# [[menu.main]]
#   identifier = "about"
#   name = "about"
#   pageRef = "/about"
#   weight = 5

[[menu.main]]
  name = "search"
  weight = 6

  [menu.main.params]
  type = "search"

[taxonomies]
author = 'authors'
year = 'years'
genre = 'genres'

[params]
favicon = "🫀"
displayUpdatedDate = true
images = ["images/face.png"]

[params.navbar]
displayTitle = true
displayLogo = false

[params.social]
twitter = 'LucianKnock'

[params.blog.list]
displaytags = true

[params.footer]
displayPoweredBy = false
displayCopyright = true

[params.page]
width = 'normal'

# [[menu.sidebar]]
# name = "More"
# weight = 1
# [menu.sidebar.params]
# type = "separator"

# [[menu.sidebar]]
# name = "About"
# pageRef = "/about"
# weight = 2
